/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#490006',
        'on-secondary-fixed': '#003a43',
        'tertiary-fixed-dim': '#4da8fe',
        'error-dim': '#d7383b',
        'surface-container-lowest': '#000000',
        'secondary-container': '#006877',
        'surface-bright': '#2c2c2c',
        'on-background': '#ffffff',
        'outline-variant': '#494847',
        'surface-container-highest': '#262626',
        error: '#ff716c',
        'on-secondary-container': '#eafbff',
        'tertiary-container': '#4da8fe',
        'on-secondary-fixed-variant': '#005966',
        'inverse-on-surface': '#565554',
        'on-primary-container': '#00555a',
        surface: '#0e0e0e',
        'on-primary-fixed': '#004145',
        'on-tertiary-fixed-variant': '#003b66',
        'surface-container-high': '#201f1f',
        'inverse-primary': '#006a70',
        'primary-dim': '#00e2ee',
        'primary-fixed-dim': '#00e2ee',
        'surface-dim': '#0e0e0e',
        background: '#0e0e0e',
        'primary-container': '#00f1fe',
        'on-primary': '#005f64',
        tertiary: '#6fb5ff',
        'surface-variant': '#262626',
        'surface-container-low': '#131313',
        'tertiary-fixed': '#6fb5ff',
        'on-tertiary': '#003258',
        outline: '#777575',
        'surface-container': '#1a1919',
        'on-tertiary-container': '#002746',
        secondary: '#00e0fe',
        'primary-fixed': '#00f1fe',
        'on-surface': '#ffffff',
        'surface-tint': '#99f7ff',
        'on-error-container': '#ffa8a3',
        'secondary-dim': '#00d1ed',
        'tertiary-dim': '#47a2f8',
        primary: '#99f7ff',
        'on-secondary': '#004b56',
        'secondary-fixed': '#4be4ff',
        'on-surface-variant': '#adaaaa',
        'error-container': '#9f0519',
        'inverse-surface': '#fcf8f8',
        'secondary-fixed-dim': '#00d7f4',
        'on-tertiary-fixed': '#001930',
        'on-primary-fixed-variant': '#006065',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
